> {% client.global.set("auth_token", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwOTcwODg4LCJpYXQiOjE3NDA5NzA1ODgsImp0aSI6Ijk3NWVjNmJiYmU1NzRjM2JhNTgxOTU5NzU2NTZkYTY0IiwidXNlcl9pZCI6MX0.sXOZSDFYh5W6zdzHSi9R1tYbGrHdERzomPG4gmM6FyU"); %}

####
#### End-points APP movies
### GET request all movies
@auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwOTcwODg4LCJpYXQiOjE3NDA5NzA1ODgsImp0aSI6Ijk3NWVjNmJiYmU1NzRjM2JhNTgxOTU5NzU2NTZkYTY0IiwidXNlcl9pZCI6MX0.sXOZSDFYh5W6zdzHSi9R1tYbGrHdERzomPG4gmM6FyU
GET http://localhost:8000/api/v1/movies
Authorization: Bearer {{auth_token}}

### POST create a new movie
POST http://localhost:8000/movies/create/
Content-Type: application/json

{
    "title": "O Irlandês",
    "release_date": "2019-02-03",
    "resume": "Um assassino lembra que tal vez esteve envolvido na morte de Jimmy Hoffa.",
    "genre": 18,
    "actors": [
        1
    ]
}

### GET detail movie
GET localhost:8000/movies/3/

### PUT update actor
PUT localhost:8000/movies/3/update
Content-Type: application/json

{
    "title": "O Irlandês",
    "release_date": "2019-02-03",
    "resume": "Um assassino lembra que tal vez esteve envolvido na morte de Jimmy Hoffa.",
    "genre": 16,
    "actors": [
        1
    ]
}

### DELETE delete actor
DELETE http://localhost:8000/movies/3/delete