### GET request all genres into database
GET http://localhost:8000/genres/

### POST create a new gender
POST http://localhost:8000/genres/create/
Content-Type: application/json

{
    "name": "Romance"
}

### GET detail genre
GET http://localhost:8000/genres/1/

### PUT update genre
PUT http://localhost:8000/genres/4/
Content-Type: application/json

{
    "name": "Suspense"
}

### DELETE delete genre
DELETE http://localhost:8000/genres/9/