####
#### End-points APP movies
### GET request all movies
GET http://localhost:8000/movies/

### POST create a new movie
POST http://localhost:8000/movies/create/
Content-Type: application/json

{
    "title": "O Irlandês",
    "release_date": "2019-02-03",
    "resume": "Um assassino lembra que tal vez esteve envolvido na morte de Jimmy Hoffa.",
    "genre": 18,
    "actors": [
        1
    ]
}

### GET detail movie
GET localhost:8000/movies/3/

### PUT update actor
PUT localhost:8000/movies/3/update
Content-Type: application/json

{
    "title": "O Irlandês",
    "release_date": "2019-02-03",
    "resume": "Um assassino lembra que tal vez esteve envolvido na morte de Jimmy Hoffa.",
    "genre": 16,
    "actors": [
        1
    ]
}

### DELETE delete actor
DELETE http://localhost:8000/movies/3/delete